"use client";

import { useState, useRef } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export default function ContractGenerator({ lead, onClose }: { lead: any, onClose: () => void }) {
    const [isGenerating, setIsGenerating] = useState(false);
    const contractRef = useRef<HTMLDivElement>(null);

    const handleGeneratePDF = async () => {
        if (!contractRef.current) return;
        setIsGenerating(true);

        try {
            const canvas = await html2canvas(contractRef.current, { 
                scale: 2,
                backgroundColor: "#ffffff",
                useCORS: true
            });
            
            const imgData = canvas.toDataURL("image/png");
            
            const pdf = new jsPDF("p", "mm", "a4");
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
            
            pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
            pdf.save(`Contract_${lead.client_name.replace(/\s+/g, '_')}.pdf`);
            
            onClose(); 
        } catch (error) {
            console.error(error);
            alert("Failed to generate PDF. Please try again.");
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4 overflow-hidden">
            
            <div className="absolute top-0 left-0 -z-20 w-[794px] h-[1123px]">
                <div ref={contractRef} className="bg-white text-black p-12 w-full h-full flex flex-col" style={{ fontFamily: 'Times New Roman, serif' }}>
                    <div className="flex justify-between items-start border-b-2 border-gray-300 pb-6 mb-10">
                        <div>
                            <h1 className="text-3xl font-black text-gray-900 tracking-tight">Prop<span className="text-[#02AFA9]">OS</span></h1>
                            <p className="text-sm text-gray-500 mt-1">Official Real Estate CRM</p>
                        </div>
                        <div className="text-right">
                            <p className="font-bold text-gray-800">AGREEMENT OF SALE / LEASE</p>
                            <p className="text-sm text-gray-500">Date: {new Date().toLocaleDateString()}</p>
                            <p className="text-sm text-gray-500">Ref: #{lead.id.split('-')[0].toUpperCase()}</p>
                        </div>
                    </div>

                    <div className="flex-1 space-y-6 text-gray-800 leading-relaxed">
                        <h2 className="text-xl font-bold border-b border-gray-200 pb-2">1. The Parties</h2>
                        <p>This document serves as an official agreement involving the following client:</p>
                        <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
                            <p><strong>Client Name:</strong> {lead.client_name}</p>
                            <p><strong>Contact Info:</strong> {lead.client_phone || lead.client_email}</p>
                        </div>

                        <h2 className="text-xl font-bold border-b border-gray-200 pb-2 mt-8">2. Property & Financial Details</h2>
                        <p>The client has expressed formal intent and agreed upon the following terms regarding the selected property:</p>
                        <div className="bg-gray-50 p-4 rounded-md border border-gray-200">
                            <p><strong>Property Type:</strong> {lead.preferred_type || "Specified Real Estate"}</p>
                            <p><strong>Agreed Amount / Budget:</strong> {Number(lead.budget).toLocaleString()} MAD</p>
                            <p><strong>Pipeline Stage:</strong> Successfully Closed (WON)</p>
                        </div>

                        <h2 className="text-xl font-bold border-b border-gray-200 pb-2 mt-8">3. Terms & Conditions</h2>
                        <p className="text-sm text-gray-600 text-justify">
                            This document generated by PropOS CRM serves as an initial summary of the transaction. Official legal transfer of title or lease agreements remain subject to local real estate laws, notary signatures, and the finalization of funds transfer. The agency confirms the receipt of intent from the aforementioned client.
                        </p>
                    </div>

                    <div className="mt-16 flex justify-between px-10">
                        <div className="text-center">
                            <p className="font-bold text-gray-800 mb-12">Client Signature</p>
                            <div className="w-48 border-t border-gray-400"></div>
                            <p className="mt-2 text-sm text-gray-500">{lead.client_name}</p>
                        </div>
                        <div className="text-center">
                            <p className="font-bold text-gray-800 mb-12">Agency Representative</p>
                            <div className="w-48 border-t border-gray-400"></div>
                            <p className="mt-2 text-sm text-gray-500">Authorized Agent</p>
                        </div>
                    </div>

                    <div className="mt-auto border-t border-gray-300 pt-4 text-center text-xs text-gray-400">
                        Generated by PropOS CRM System • Confidential & Proprietary
                    </div>
                </div>
            </div>

            <div className="absolute inset-0 bg-[#222231]/95 backdrop-blur-xl -z-10" onClick={onClose}></div>

            <div className="w-full max-w-[500px] bg-[#2a2a3c] border border-[#02AFA9]/30 rounded-2xl p-6 shadow-2xl relative flex flex-col items-center text-center z-10">
                <div className="w-16 h-16 rounded-full bg-[#02AFA9]/20 flex items-center justify-center text-[#02AFA9] mb-4">
                    <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                </div>
                
                <h2 className="text-xl font-bold text-white mb-2">Generate Official Contract</h2>
                <p className="text-sm text-white/60 mb-6 leading-relaxed">
                    You are about to generate a legally formatted PDF document for <strong className="text-white">{lead.client_name}</strong> for the amount of <strong className="text-[#02AFA9]">{Number(lead.budget).toLocaleString()} MAD</strong>.
                </p>

                <div className="flex gap-3 w-full">
                    <button onClick={onClose} disabled={isGenerating} className="flex-1 h-11 rounded-lg bg-[#1a1a24] border border-white/10 text-xs font-bold uppercase tracking-wider text-white/70 hover:text-white hover:bg-white/5 transition-colors disabled:opacity-50 cursor-pointer">
                        Cancel
                    </button>
                    <button onClick={handleGeneratePDF} disabled={isGenerating} className="flex-1 h-11 rounded-lg bg-[#02AFA9] text-xs font-bold uppercase tracking-wider text-white hover:bg-[#05bbb5] transition-colors disabled:opacity-50 shadow-[0_8px_20px_rgba(2,175,169,0.30)] flex items-center justify-center gap-2 cursor-pointer">
                        {isGenerating ? (
                            <span className="animate-pulse">Processing...</span>
                        ) : (
                            <>
                                <span>Download PDF</span>
                                <svg className="w-4 h-4 pointer-events-none" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                            </>
                        )}
                    </button>
                </div>
            </div>

        </div>
    );
}